export const FETCH_ALL_BY_USERNAME = 'FETCH_ALL_BY_USERNAME';
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
export const FETCH_POST_BY_ID_FAIL = 'FETCH_POST_BY_ID_FAIL';
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const LIKE = 'LIKE';
export const COMMENT = 'COMMENT';

export const AUTH = 'AUTH';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOADING = 'AUTH_LOADING';
export const REGISTER = 'REGISTER';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_RESET = 'AUTH_RESET';
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const GET_USER = "GET_USER";
export const GET_USERS_BY_SEARCH = "GET_USERS_BY_SEARCH";
export const EDIT_ACCOUNT = "EDIT_ACCOUNT";
export const EDIT_ACCOUNT_FAIL = "EDIT_ACCOUNT_FAIL";
export const EDIT_PASSWORD = "EDIT_PASSWORD";
export const EDIT_PASSWORD_FAIL = "EDIT_PASSWORD_FAIL";

export const GET_ALL_TIMES = 'GET_ALL_TIMES';
export const ADD_NEW_TIME = "ADD_NEW_TIME";
export const DELETE_TIME = "DELETE_TIME";
export const DELETE_ALL_TIMES = "DELETE_ALL_TIMES";
export const SET_DNF = "SET_DNF";
export const SET_TIME_OK = "SET_TIME_OK";
export const SET_PLUS_TWO = "SET_PLUS_TWO";

export const GET_ALL_SESSIONS = "GET_ALL_SESSIONS";
export const ADD_NEW_SESSION = "ADD_NEW_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";
export const RESET_SESSION = "RESET_SESSION";

export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const GET_TUTORIALS_BY_USERNAME = "GET_TUTORIALS_BY_USERNAME";
export const DELETE_TUTORIAL_BY_ID = "DELETE_TUTORIAL_BY_ID";
export const GET_TUTORIAL_BY_ID = "GET_TUTORIAL_BY_ID";
export const GET_TUTORIAL_BY_ID_FAIL = "GET_TUTORIAL_BY_ID_FAIL";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const TUTORIAL_LOADING = "TUTORIAL_LOADING";

export const CREATE_CONTEST = "CREATE_CONTEST";
export const GET_ALL_CONTESTS = "GET_ALL_CONTESTS";
export const DELETE_CONTEST_BY_ID = "DELETE_CONTEST_BY_ID";
export const DELETE_CONTEST_END_BY_ID = "DELETE_CONTEST_END_BY_ID";
export const GET_CONTEST_BY_ID = "GET_CONTEST_BY_ID";
export const GET_CONTEST_BY_ID_FAIL = "GET_CONTEST_BY_ID_FAIL";
export const UPDATE_CONTEST = "UPDATE_CONTEST";
export const ADD_USER_TO_CONTEST = "ADD_USER_TO_CONTEST";
export const GET_CONTEST_EVENT = "GET_CONTEST_EVENT";
export const SET_CONTEST_ENDED = "SET_CONTEST_ENDED";
export const SET_CONTEST_RESUMED = "SET_CONTEST_RESUMED";
export const RESET_CONTEST = "RESET_CONTEST";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const BAD_REQUEST_FALSE = "BAD_REQUEST_FALSE"
export const BAD_REQUEST_TRUE = "BAD_REQUEST_TRUE"
export const BAD_REQUEST_RESET = "BAD_REQUEST_RESET"

export const VERIFY_REGISTER_EMAIL = "VERIFY_REGISTER_EMAIL"
export const VERIFY_REGISTER_EMAIL_FAIL = "VERIFY_REGISTER_EMAIL_FAIL"